### ISSUE TITLE
Convert scripts to run into PostgreSQL instead terminal

### ISSUE THREAD

**Issue by ppKrauss** [iburadempa/pg_jts#4]
All scripts can be adapted to use as [PL-Python stored procedures](https://www.postgresql.org/docs/current/static/plpython.html), so "all into the database", so better performance and universal use.  I can help to do it.

**Comment by iburadempa** [comment]
As one of the main use cases for this package I see visualizing structures of existing databases (often on servers running for years with hardly documented software written by people who have long left) and thereby better understanding a running system. As exporting the structure happens only once, performance is hardly an issue here. And if possible, it should not be necessary to modify the running database system (like installing PL/Python and restarting postgres it and possibly installing a suitable python interpreter). Nevertheless, thanks for offering your help.
