### ISSUE TITLE
pg_jts was replaced by tableschema-sql-py?

### ISSUE THREAD

**Issue by ppKrauss** [iburadempa/pg_jts#5]
Seems they do similar things, https://github.com/frictionlessdata/tableschema-sql-py

...so, community is abandoning `pg_jts` to use `tableschema_sql`?

**Comment by iburadempa** [comment]
If I read the documentation of tableschema-sql-py correctly, it aims at the reverse direction, namely from a given tableschema to a database. pg_jts extracts more schema information from a postgresql database than required by the JSON-tableschema specification, in particular postgresql-specific structures. It still tries to remain compatble with the JSON-tableschema specification (which leaves room for that). It also targets a whole database and the relations between its tables. (They are not part of the JSON-tableschema.)
I have no information on what "community" is doing in this context.
